### ISSUE TITLE
`AttributeError: __name__` when printing captures

### ISSUE THREAD

**Issue by jcaw** [talonvoice/beta#29]
Getting a strange error when I try to print captures. Minimal example:

```python
>>> registry.decls.captures
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "talon\scripting\types.py", line 167, in __repr__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\typing.py", line 702, in __getattr__
AttributeError: __name__
```

Accessing `keys` works, but accessing `values` triggers it.

**Comment by lunixbochs** [comment]
fixed in next release
